image: registry.gitlab.com/han-thesis/fluids

stages:
  - test
  - publish

unittest:
  type: test

  before_script:
    - docker login -u $CI_USER -p $CI_BUILD_TOKEN registry.gitlab.com

  script:
    - mkdir -p build
    - cd build
    - cmake -DCMAKE_BUILD_TYPE=Release ..
    - make
    - ./test/test_main

release:
  type: publish

  before_script:
    - docker login -u $CI_USER -p $CI_BUILD_TOKEN registry.gitlab.com

  script:
    - mkdir -p build
    - cd build
    - cmake -DCMAKE_BUILD_TYPE=Release ..
    - make
    - cpack -G TGZ
    - mv *.tar.gz ..
    - cd ..

  artifacts:
    paths:
      - ./*.tar.gz